name: JEST
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: npm run test
